module.exports = {
  taskId: "843B914B-C304-4887-BC09-92F3F31000C7",
  pluginVersion: "4.2.5",
  reference: "sketch",
  type: "Block",
  id: "Block_1",
  __VERSION__: "2.0",
  props: { style: { width: 700, height: 270 }, attrs: { x: 0, y: 0 } },
  artboardImg:
    "https://static.imgcook.com/img/test/ea398100ebf711eda53abd428b76e35a.png",
  children: [
    {
      __VERSION__: "2.0",
      props: {
        style: {
          backgroundColor: "#FFFCF7",
          borderTopLeftRadius: 20,
          borderTopRightRadius: 20,
          borderBottomRightRadius: 20,
          borderBottomLeftRadius: 20,
          overflow: "hidden",
          width: 700,
          height: 270,
        },
        attrs: { x: 0, y: 0 },
      },
      type: "Shape",
      selfId: "C83C14E8-AA20-4F77-B016-5CE9B0459123",
      children: [],
      originType: "ShapePath",
      nodeLayerName: "Rectangle 1",
      id: "Shape_0",
    },
    {
      __VERSION__: "2.0",
      props: {
        style: {
          backgroundColor: "#FFF6DB",
          borderTopLeftRadius: 20,
          borderTopRightRadius: 20,
          borderBottomRightRadius: 20,
          borderBottomLeftRadius: 20,
          overflow: "hidden",
          width: 265,
          height: 122,
        },
        attrs: { x: 44, y: 71 },
      },
      type: "Shape",
      selfId: "8185D0D5-8461-43EC-A5AD-0FEA043FC886",
      children: [],
      originType: "ShapePath",
      nodeLayerName: "Rectangle 2",
      id: "Shape_1",
    },
    {
      __VERSION__: "2.0",
      props: {
        style: {
          backgroundColor: "#FFF6DB",
          borderTopLeftRadius: 20,
          borderTopRightRadius: 20,
          borderBottomRightRadius: 20,
          borderBottomLeftRadius: 20,
          overflow: "hidden",
          width: 265,
          height: 122,
        },
        attrs: { x: 376, y: 71 },
      },
      type: "Shape",
      selfId: "ED4FD02C-D948-4300-A8FA-61DE98D7F3BC",
      children: [],
      originType: "ShapePath",
      nodeLayerName: "Rectangle 3",
      id: "Shape_2",
    },
    {
      __VERSION__: "2.0",
      props: {
        style: {
          color: "rgba(0, 0, 0, 1)",
          fontFamily: "PingFang SC",
          fontSize: 40,
          fontWeight: "normal",
          lineHeight: 47,
          width: 25,
          height: 47,
        },
        attrs: { x: 330, y: 104, text: "=", lines: 1 },
      },
      type: "Text",
      selfId: "9F3CE407-F237-49B6-9047-09D0A1F2F9490",
      children: [],
      originType: "Other",
      nodeLayerName: "=",
      id: "Text_3",
    },
    {
      __VERSION__: "2.0",
      props: {
        style: {
          color: "rgba(51, 51, 51, 1)",
          fontFamily: ".PingFang SC",
          fontSize: 32,
          fontWeight: 400,
          lineHeight: 38,
          width: 128,
          height: 38,
        },
        attrs: { x: 111, y: 205, text: "全国通用", lines: 1 },
      },
      type: "Text",
      selfId: "CBDC5853-C51D-4A12-AB60-D71EA3184FDD0",
      children: [],
      originType: "Other",
      nodeLayerName: "全国通用",
      id: "Text_4",
    },
    {
      __VERSION__: "2.0",
      props: {
        style: {
          color: "rgba(249, 69, 51, 1)",
          fontFamily: "PingFang SC",
          fontSize: 32,
          fontWeight: "normal",
          lineHeight: 38,
          width: 16,
          height: 38,
        },
        attrs: { x: 199, y: 119, text: "/", lines: 1 },
      },
      type: "Text",
      selfId: "E9031EA3-783C-443D-9E7D-98E364FD6A5A0",
      children: [],
      originType: "Other",
      nodeLayerName: "/月包",
      id: "Text_5",
    },
    {
      __VERSION__: "2.0",
      props: {
        style: {
          color: "rgba(249, 69, 51, 1)",
          fontFamily: ".PingFang SC",
          fontSize: 32,
          fontWeight: 400,
          lineHeight: 38,
          width: 64,
          height: 38,
        },
        attrs: { x: 215, y: 119, text: "月包", lines: 1 },
      },
      type: "Text",
      selfId: "E9031EA3-783C-443D-9E7D-98E364FD6A5A1",
      children: [],
      originType: "Other",
      nodeLayerName: "/月包",
      id: "Text_6",
    },
    {
      __VERSION__: "2.0",
      props: {
        style: {
          color: "rgba(249, 69, 51, 1)",
          fontFamily: ".PingFang SC",
          fontSize: 32,
          fontWeight: 400,
          lineHeight: 38,
          width: 41,
          height: 38,
        },
        attrs: { x: 513, y: 119, text: " 元", lines: 1 },
      },
      type: "Text",
      selfId: "542D5CF1-8F9D-4135-8412-11733CDE796F0",
      children: [],
      originType: "Other",
      nodeLayerName: "元/月",
      id: "Text_7",
    },
    {
      __VERSION__: "2.0",
      props: {
        style: {
          color: "rgba(249, 69, 51, 1)",
          fontFamily: "PingFang SC",
          fontSize: 32,
          fontWeight: "normal",
          lineHeight: 38,
          width: 16,
          height: 38,
        },
        attrs: { x: 554, y: 119, text: "/", lines: 1 },
      },
      type: "Text",
      selfId: "542D5CF1-8F9D-4135-8412-11733CDE796F1",
      children: [],
      originType: "Other",
      nodeLayerName: "元/月",
      id: "Text_8",
    },
    {
      __VERSION__: "2.0",
      props: {
        style: {
          color: "rgba(249, 69, 51, 1)",
          fontFamily: ".PingFang SC",
          fontSize: 32,
          fontWeight: 400,
          lineHeight: 38,
          width: 32,
          height: 38,
        },
        attrs: { x: 570, y: 119, text: "月", lines: 1 },
      },
      type: "Text",
      selfId: "542D5CF1-8F9D-4135-8412-11733CDE796F2",
      children: [],
      originType: "Other",
      nodeLayerName: "元/月",
      id: "Text_9",
    },
    {
      __VERSION__: "2.0",
      props: {
        style: {
          color: "rgba(51, 51, 51, 1)",
          fontFamily: ".PingFang SC",
          fontSize: 32,
          fontWeight: 400,
          lineHeight: 38,
          width: 128,
          height: 38,
        },
        attrs: { x: 445, y: 205, text: "自动续订", lines: 1 },
      },
      type: "Text",
      selfId: "8240ECC1-BC0B-4FE4-BB26-B688AEA1516D0",
      children: [],
      originType: "Other",
      nodeLayerName: "自动续订",
      id: "Text_10",
    },
    {
      __VERSION__: "2.0",
      props: {
        style: { width: 316, height: 48 },
        attrs: {
          x: 192,
          y: 0,
          source:
            "https://static.imgcook.com/img/test/ea2b5030ebf711eda55e4b65341976b8.png",
        },
      },
      type: "Image",
      selfId: "8A919E8B-1BB5-4287-B943-18F2E4313309",
      children: [],
      originType: "ShapePath",
      nodeLayerName: "路径",
      id: "Image_11",
    },
    {
      __VERSION__: "2.0",
      props: {
        style: {
          color: "rgba(255, 255, 255, 1)",
          fontFamily: ".PingFang SC",
          fontSize: 32,
          fontWeight: 400,
          lineHeight: 38,
          width: 160,
          height: 38,
        },
        attrs: { x: 270, y: 0, text: "流量超值购", lines: 1 },
      },
      type: "Text",
      selfId: "A023BFC9-AF67-4242-AFB6-F7D2D3194F420",
      children: [],
      originType: "Other",
      nodeLayerName: "流量超值购",
      id: "Text_12",
    },
    {
      __VERSION__: "2.0",
      props: {
        style: {
          color: "rgba(249, 69, 51, 1)",
          fontFamily: "PingFang SC",
          fontSize: 64,
          fontWeight: "normal",
          lineHeight: 76,
          width: 130,
          height: 76,
        },
        attrs: { x: 74, y: 93, text: "5GB", lines: 1 },
      },
      type: "Text",
      selfId: "6802F756-D177-4CA3-A539-F2532495706C0",
      children: [],
      originType: "Other",
      nodeLayerName: "5GB",
      id: "Text_13",
    },
    {
      __VERSION__: "2.0",
      props: {
        style: {
          color: "rgba(249, 69, 51, 1)",
          fontFamily: "PingFang SC",
          fontSize: 64,
          fontWeight: "normal",
          lineHeight: 76,
          width: 94,
          height: 76,
        },
        attrs: { x: 425, y: 93, text: "9.9", lines: 1 },
      },
      type: "Text",
      selfId: "A4DA75BE-FB32-4DC2-A883-F82500CE4ACE0",
      children: [],
      originType: "Other",
      nodeLayerName: "9.9",
      id: "Text_14",
    },
  ],
  name: "icon区_利益点",
};
